<!DOCTYPE html>
<html lang="ru">
<head>
    <title>Сайт Даниила</title>
    <meta charset="UTF-8">
    <a href="update_table.php" class="button">Заполнить табель</a>
    <style>
        .button {
            background-color: #4CAF50;
            border: none;
            color: white;
            padding: 15px 32px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 16px;
            margin: 4px 2px;
            cursor: pointer;
        }
        /* This CSS will style the table generated by PHP. */
        table { border-collapse: collapse; width: 30em; font-size: 1.2em; }
        table, th, td { border: 2px solid #232323; }
        td,th { padding: 0.5em; }
        /* Create a striped table. */
        tr:nth-child(even) { background-color: #ffffff; }
        /* General body styles. */
        body { display: grid; justify-content: center; align-items: center; height: 100vh; }
    </style>
</head>
    <body>
    <main>
        <script type="text/javascript" href="./js/javascript.js"></script>

<?php
error_reporting(0);
$db_host = 'localhost';
$db_user = 'root';
$db_password = '';
$db_name = 'api_db';

$link = mysqli_connect($db_host, $db_user, $db_password, $db_name);
if (!$link) {
    die('<p style="color:red">'.mysqli_connect_errno().' - '.mysqli_connect_error().'</p>');
}
else {
    echo "<p>Вы подключились к MySQL!</p>";
}
$color_array = ['black', 'red', 'green', 'blue'];
$query = mysqli_query($link,'SELECT * FROM report_card')->fetch_all(MYSQLI_ASSOC);
$table_header = ["Номер записи", "Оператор", "Время работы", "Время суток", "Цена", "Дата:время"];
echo "<table>";
// Print the table headers.

echo "<tr>";

foreach ($table_header as $val) {
    echo "<th text-align='left'>" . $val . "</th>";
    }
echo "</tr>";
    foreach ($query as $row) {
        echo "<tr>";
        foreach ($row as $value) {
            if (is_null($value)) {
                echo "<td>NULL</td>";
            } else {
                echo "<td>" . $value . "</td>";
            }
        }
        echo "</tr>";
    }
    echo "</table>";

echo "</tr>";
echo '</ul>';

?>
    </main>
    </body>